
name = 'pybattle'
licence = "GNU"

[author]
name = "Jacob Ophoven"
user.github = "PythonDominator"

[repo]
name = "Pybattle"
url = "https://github.com/PythonDominator/Pybattle"
desc = "A python ascii text art pokemon style game in the terminal using ANSI escape codes."

[requirements]
python-version = ">=3.11"

[version]

[version.main]
beta = true
alpha = false
other = false

[version.update]
add = 0
other = false

[version.end]
other = false
