name: Running

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: download python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: run
        run: python pybattle/types_.py
    
